services:
  poc-api:
    image: ${ECR_REGISTRY}/$ECR_REPOSTIORY:${ENVIRONMENT}-${IMAGE_TAG}
    pull_policy: if_not_present
    ports:
      - '5000:5000'
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DEBUG: false
      PATH_ASSET: public/uploads
      BASE_URL: http://127.0.0.1:5000
      BASE_URL_FE: http://127.0.0.1
      JWT_TOKEN: poc
      JWT_REFRESH_TOKEN: poc-refresh
      JWT_TOKEN_EXPIRED: 15780000
      JWT_REFRESH_TOKEN_EXPIRED: 31560000
      DEFAULT_PASSWORD: poc123
      MAIL_DEBUG: false
      MAIL_HOST: mail.com
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
      MAIL_PORT: 578
      MAIL_SERVER: server
      TOKEN_TELEGRAM: ${TOKEN_TELEGRAM}
      CHAT_ID_TELEGRAM: ${CHAT_ID_TELEGRAM}
    command: >
      sh -c "npm run db:migrate && npm start"
